name: tyrants
jobs:
  BuildModel:
    name: Build model
    steps:
      - type: node-js
        working-directory: ./totuModel
        name: Install npm dependencies
        shell-script: |-
          npm ci
          npm install -D ts-proto
        docker-image: node:lts
      - type: gradle
        working-directory: ''
        use-gradle-wrapper: 'true'
        tasks: ':totuModel:build'
        jdk-home: '%env.JDK_21_0_x64%'
      - type: node-js
        working-directory: ''
        shell-script: |-
          apt-get update
          apt-get install protobuf-compiler -y
          npm run build-model
        docker-image: node:lts
        name: Build npm package
    runs-on: Linux-Small
    parallelism: 5
    enable-dependency-cache: true
    files-publication:
      - ./totuModel/build/libs/*.jar
      - ./totuModel/*.tgz
      - ./totuModel/dist/**
    checkout-working-directories-only: false
    allow-reuse: false
  PublishGradle:
    name: Publish Gradle model package
    runs-on: Linux-Small
    dependencies:
      - BuildModel:
          files:
            - ./totuModel/build/libs/*.jar
            - ./totuModel/*.tgz
            - ./totuModel/dist/**
    steps:
      - type: script
        working-directory: ''
        name: Set environment vars and publish
        script-content: >-
          export GIT_USERNAME=%USERNAME%
          export GIT_PASSWORD=%GITHUB_TOKEN%
          ./gradlew verifyRelease -PGIT_USERNAME=%USERNAME% -PGIT_PASSWORD=%GITHUB_TOKEN%

          if [ $? -eq 0 ]; then
              ./gradlew versionBump -PGIT_USERNAME=%USERNAME% -PGIT_PASSWORD=%GITHUB_TOKEN%
              ./gradlew :totuModel:release -PGIT_USERNAME=%USERNAME% -PGIT_PASSWORD=%GITHUB_TOKEN%
              ./gradlew :totuModel:publish -PGIT_USERNAME=%USERNAME% -PGIT_PASSWORD=%GITHUB_TOKEN%
          else
              echo "No release needed"
          fi
    enable-dependency-cache: true
    files-publication:
      - ./totuModel/build/libs/*.jar
    checkout-working-directories-only: false
    allow-reuse: false
  PublishNPM:
    name: Publish NPM model package
    runs-on: Linux-Small
    dependencies:
      - BuildModel:
          files:
            - ./totuModel/build/libs/*.jar
            - ./totuModel/*.tgz
            - ./totuModel/dist/**
    steps:
      - type: node-js
        shell-script: >-
          # Exports refer: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md
          export GITHUB_TOKEN=%GITHUB_TOKEN%
          export GH_TOKEN=%GITHUB_TOKEN%
          export NPM_TOKEN=%GITHUB_TOKEN%

          npm ci
          npm run release-model
        docker-image: node:lts
        working-directory: ''
        name: Publish NPM model package
    enable-dependency-cache: true
    files-publication:
      - ./totuModel/*.tgz
      - ./totuModel/dist/**
    checkout-working-directories-only: false
    allow-reuse: false
secrets:
  GITHUB_TOKEN: credentialsJSON:74211c03-3550-4c65-9eb3-b262fd2f893d
parameters:
  USERNAME: junomars
