name: tyrants
jobs:
  BuildModel:
    name: Build model
    steps:
      - type: node-js
        working-directory: ./totuModel
        name: ''
        shell-script: |-
          npm ci
          npm install -D ts-proto
        docker-image: node:lts
      - type: gradle
        working-directory: ''
        use-gradle-wrapper: 'true'
        tasks: ':totuModel:build'
        jdk-home: '%env.JDK_21_0_x64%'
      - type: node-js
        working-directory: ./totuModel
        shell-script: |-
          apt-get update
          apt-get install protobuf-compiler -y
          npm run build
        docker-image: node:lts
        name: Build npm package
    runs-on: Linux-Small
    parallelism: 5
    enable-dependency-cache: true
    files-publication:
      - ./totuModel/build/libs/*.jar
      - ./totuModel/*.tgz
      - ./totuModel/dist/**
  PublishGradle:
    name: Publish Gradle model package
    runs-on: Linux-Small
    dependencies:
      - BuildModel:
          files:
            - ./totuModel/build/libs/*.jar
            - ./totuModel/*.tgz
            - ./totuModel/dist/**
    steps:
      - type: gradle
        working-directory: ''
        use-gradle-wrapper: 'true'
        tasks: ':totuModel:publish -Pgpr.user=%USERNAME% -Pgpr.token=%GITHUB_TOKEN%'
        jdk-home: '%env.JDK_21_0_x64%'
        name: Publish Gradle model package
    enable-dependency-cache: true
    files-publication:
      - ./totuModel/build/libs/*.jar
    parallelism: 5
  PublishNPM:
    name: Publish NPM model package
    runs-on: Linux-Small
    steps:
      - type: node-js
        shell-script: |-
          cd totuModel
          npm ci
          npm run release
        docker-image: node:lts
        working-directory: ''
        name: Publish NPM model package
    dependencies:
      - BuildModel:
          files:
            - ./totuModel/build/libs/*.jar
            - ./totuModel/*.tgz
            - ./totuModel/dist/**
    files-publication:
      - ./totuModel/*.tgz
      - ./totuModel/dist/**
secrets:
  GITHUB_TOKEN: credentialsJSON:ece132ad-c40d-4fd9-af78-c4e4b02e0042
parameters:
  USERNAME: junomars
