name: tyrants
jobs:
  BuildModel:
    name: Build packages
    steps:
      - type: node-js
        working-directory: ./totuModel
        name: ''
        shell-script: |-
          sudo apt-get install protobuf-compiler
          npm ci
        docker-image: node:lts
      - type: gradle
        working-directory: ./totuModel
        use-gradle-wrapper: ''
        tasks: build
        jdk-home: '%env.JDK_21_0_x64%'
      - type: gradle
        working-directory: ./totuServer
        tasks: build
        jdk-home: '%env.JDK_21_0_x64%'
      - type: node-js
        working-directory: ./totuClient
        shell-script: npm run build
        docker-image: node:lts
    runs-on: Linux-Small
    parallelism: 5
    enable-dependency-cache: true
