/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/game/board/Board.vue')['default']
    Circle: typeof import('./src/components/base/Circle.vue')['default']
    Game: typeof import('./src/components/game/Game.vue')['default']
    GameBoard: typeof import('./src/components/game/board/GameBoard.vue')['default']
    GameView: typeof import('./src/components/game/GameView.vue')['default']
    Graph: typeof import('./src/components/game/board/Graph.vue')['default']
    Node: typeof import('./src/components/Node.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Site: typeof import('./src/components/game/board/Site.vue')['default']
    Spike: typeof import('./src/components/base/Spike.vue')['default']
    SpikyCircle: typeof import('./src/components/game/SpikyCircle.vue')['default']
    Text: typeof import('./src/components/base/Text.vue')['default']
    TroopSpace: typeof import('./src/components/game/board/TroopSpace.vue')['default']
  }
}
